name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            👋 Hey there! Thanks for opening your first issue in the **IOC Hunter** repo.

            This project helps convert pasted IOCs into actionable SIEM queries across platforms like Elastic, Sentinel, and Splunk. Feel free to share ideas, bugs, or enhancements—we’re excited to collaborate!

            If you're new here, check out the [README](https://github.com/0xPrashanthSec/IOCQuery) to get started.
          
          pr-message: |
            🎉 Welcome aboard! Thanks for submitting your first pull request to **IOC Hunter**.

            Your contribution helps make threat detection more accessible and automated across SIEM platforms. We’ll review your code shortly—meanwhile, feel free to explore the repo and join the conversation.

            Curious about how IOCs are parsed and mapped to ECS fields? Dive into the [README](https://github.com/0xPrashanthSec/IOCQuery) or ping us with questions!
